version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: midnighter/starlette-delay:latest
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
    - ".:/app/"
#    environment:
#    - PYTHONASYNCIODEBUG=1
#    - PYTHONWARNINGS=default
#    command: uvicorn --host 0.0.0.0 --access-log --reload --log-level debug app:app

  manager:
    image: locustio/locust:1.0.2
    ports:
     - "${WEB_PORT:-8089}:8089"
    volumes:
      - "./locust:/mnt/locust"
    depends_on:
      - web
    command: >
      -f /mnt/locust/locustfile.py
      --master
      --host http://web:${API_PORT:-8000}
      --step-load
      --step-users 10
      --step-time 10s


  worker:
    image: locustio/locust:1.0.2
    volumes:
      - "./locust:/mnt/locust"
    depends_on:
      - manager
    command: -f /mnt/locust/locustfile.py --worker --master-host manager
